In [28]:
import numpy as np
import pandas as pd

zeros3x4 = np.zeros((3,4))
print(zeros3x4)

ones2x3 = np.ones((2,3))
print(ones2x3)

empty3x5 = np.empty((3,5))
print(empty3x5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]


In [30]:
print(np.arange(10, 20, 0.5))
print(np.linspace(0, 8, 3))
print(np.arange(0, 8, 3))

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]
[0. 4. 8.]
[0 3 6]


In [31]:
array2x3 = np.array([[1, 2, 3], [4, 5, 6]])

array2x3.ndim
array2x3.shape[0]
array2x3.size
array2x3.dtype

dtype('int64')

In [32]:
ar_str = np.array([1, 2, 3], dtype=str)
print(ar_str)
ar_float = ar_str.astype(np.float64)
print(ar_float)
ar_comp = ar_str.astype(np.complex128)
print(ar_comp)

['1' '2' '3']
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [33]:
ar = np.array([1, 2, 3, 4, 5, 6])
print(ar)
ar2x3 = ar.reshape(2, 3)
print(ar2x3)

a = ar2x3.ravel()
print(a)
ar2x3_T = ar2x3.T
print(ar2x3_T)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [34]:
arr3x5 = np.arange(15).reshape(3, 5)
print(arr3x5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
arr2x3x2x3 = np.arange(36).reshape(2, 3, 2, 3)
print(arr2x3x2x3)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]]


In [36]:
arr = np.arange(0,120, 3).reshape(2, 5, -1)
print(arr)

[[[  0   3   6   9]
  [ 12  15  18  21]
  [ 24  27  30  33]
  [ 36  39  42  45]
  [ 48  51  54  57]]

 [[ 60  63  66  69]
  [ 72  75  78  81]
  [ 84  87  90  93]
  [ 96  99 102 105]
  [108 111 114 117]]]


In [37]:
a = np.array(list('あいうえおか'))
a[::2]
a[::-1]

array(['か', 'お', 'え', 'う', 'い', 'あ'], dtype='<U1')

In [38]:
b = np.arange(25).reshape(5,5)
print(b)
b[range(5),range(5)]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  6, 12, 18, 24])

In [39]:
a = np.arange(100,500,100).reshape(2,2)
print(a)

for i, v in np.ndenumerate(a):
    print(f"{i}: {v}")

[[100 200]
 [300 400]]
(0, 0): 100
(0, 1): 200
(1, 0): 300
(1, 1): 400


In [40]:
a = np.arange(20).reshape(4,5)
print(a)
print(np.select([a<5, a==7, a>10], [-1, a, a*10]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ -1  -1  -1  -1  -1]
 [  0   0   7   0   0]
 [  0 110 120 130 140]
 [150 160 170 180 190]]


In [41]:
ar = np.arange(1,26).reshape(5,5)
print(ar)
ar2 = ar[1:3,1:3]
print(ar2)

ar3 = np.where([ar % 5 == 0], "5の倍数", "5の倍数ではない")
for i,v in np.ndenumerate(ar3):
    row = i[0]
    col = i[1]
    print(f"({row},{col}): {v}")
    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8]
 [12 13]]
(0,0): 5の倍数ではない
(0,0): 5の倍数ではない
(0,0): 5の倍数ではない
(0,0): 5の倍数ではない
(0,0): 5の倍数
(0,1): 5の倍数ではない
(0,1): 5の倍数ではない
(0,1): 5の倍数ではない
(0,1): 5の倍数ではない
(0,1): 5の倍数
(0,2): 5の倍数ではない
(0,2): 5の倍数ではない
(0,2): 5の倍数ではない
(0,2): 5の倍数ではない
(0,2): 5の倍数
(0,3): 5の倍数ではない
(0,3): 5の倍数ではない
(0,3): 5の倍数ではない
(0,3): 5の倍数ではない
(0,3): 5の倍数
(0,4): 5の倍数ではない
(0,4): 5の倍数ではない
(0,4): 5の倍数ではない
(0,4): 5の倍数ではない
(0,4): 5の倍数


In [42]:
a = np.array([5, 3, 4, 6, 9])
b = np.array([1, 1, 2, -1, np.inf])

print(a+b)
print(a - b)
print(a * b)
print(a - 4)
print(a ** b)
np.sqrt(a)
print(a ** 2)
print(a / b)

c = np.array([8, 6, 13, 2, 7])
print(c / a )
print(c // a)
print(c % a)
print(a.dot(c.T))
print(c.dot(a.T))

[ 6.  4.  6.  5. inf]
[  4.   2.   2.   7. -inf]
[ 5.  3.  8. -6. inf]
[ 1 -1  0  2  5]
[ 5.          3.         16.          0.16666667         inf]
[25  9 16 36 81]
[ 5.  3.  2. -6.  0.]
[1.6        2.         3.25       0.33333333 0.77777778]
[1 2 3 0 0]
[3 0 1 2 7]
185
185


In [43]:
f = np.array([-1.5, -0.8, 0., 0.5, 0.8, 1.3, 1.5, 2.5])
print(np.round(f))
print(np.floor(f)) # 負の値も切り捨てする
print(np.trunc(f).astype(int))
print(np.trunc(f)) # 負の値の場合は切り上げ
print(np.ceil(f)) # 切り上げ
print(np.fix(f)) # 0に近い方を採用


[-2. -1.  0.  0.  1.  1.  2.  2.]
[-2. -1.  0.  0.  0.  1.  1.  2.]
[-1  0  0  0  0  1  1  2]
[-1. -0.  0.  0.  0.  1.  1.  2.]
[-1. -0.  0.  1.  1.  2.  2.  3.]
[-1. -0.  0.  0.  0.  1.  1.  2.]


In [44]:
a = np.array([1, 2, 3, 0])
b = np.array([10, 2, 3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11  4  6  4]
[-9  0  0 -4]
[10  4  9  0]
[0.1 1.  1.  0. ]


In [45]:
f = np.array([-0.8, -0.2, 0., 1.2, 1.5, 1.8])
print(np.round(f).astype(int))
print(np.ceil(f).astype(int))
print(np.fix(f).astype(int))

[-1  0  0  1  2  2]
[0 0 0 2 2 2]
[0 0 0 1 1 1]


In [46]:
ar = np.arange(25).reshape(5,5)
print(ar)
print(ar.mean(axis=0))
print(ar.mean(axis=1))
print(ar.cumsum(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[10. 11. 12. 13. 14.]
[ 2.  7. 12. 17. 22.]
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]
 [50 55 60 65 70]]


In [47]:
np.random.seed(seed=0)
print(np.random.rand(5,3))
print(np.random.randint(10, 50))
a = [0, 1, 2, 3]
np.random.shuffle(a)
print(np.random.choice(a))
print(a)
print(np.random.choice(a))


[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]
19
1
[2, 1, 3, 0]
3


In [48]:
np.random.uniform(0, 1)
np.random.normal(0, 1)
np.random.poisson(1.4)

3

In [49]:
a = np.random.randint(100, 200, size=1000).reshape(250, 4)
print(a.mean(axis=1))

[140.75 140.75 148.   122.25 134.75 133.75 141.   143.5  151.   147.75
 154.25 144.5  153.   143.25 162.75 158.75 153.25 152.75 155.   126.
 145.75 149.25 172.25 162.5  135.   149.25 126.75 141.5  136.25 155.75
 130.75 155.75 153.   161.5  145.25 162.25 131.25 146.5  152.25 149.75
 157.5  138.25 155.25 157.   144.   164.5  157.75 139.75 123.5  162.
 142.5  142.5  136.5  147.25 113.25 145.5  171.75 147.25 129.   159.
 133.   161.75 144.   131.75 153.   131.75 170.25 141.5  144.   166.75
 150.25 187.25 160.   141.25 154.25 145.5  175.75 162.25 151.75 166.75
 128.25 154.   168.   138.25 123.   136.75 150.5  166.5  150.5  148.
 140.25 168.75 170.25 142.   150.   124.5  147.   150.5  181.25 149.5
 125.   149.   149.25 135.5  138.25 143.25 136.5  147.25 157.75 157.
 139.75 171.25 171.75 129.   116.   165.5  136.75 147.25 161.5  140.5
 164.25 177.5  183.25 131.5  146.   147.25 144.5  188.75 154.75 167.5
 139.   164.5  141.5  158.5  149.5  174.   144.75 179.5  161.75 133.
 146.   132.75 154.  

In [50]:
u = np.random.uniform(size=100000)
print(f"{u.mean():.2f}±{u.std():.2f}")
ran = np.random.randn(100000)
print(f"{ran.mean():.2f}±{ran.std():.2f}")

0.50±0.29
0.01±1.00


In [51]:
df = pd.DataFrame({"年齢": [12, 14, 13],
                  "性別": ["M", "M", "F"],
                  "身長": [150, 160, 152],
                 "体重": [40, 55, 48]},
                 columns = ["年齢", "性別", "身長", "体重"])
print(df)
print(df.columns)
print(df.index)
df.index = ["Taro", "Jiro", "Hana"]
print(df.index)
print(df)
display(df)

   年齢 性別   身長  体重
0  12  M  150  40
1  14  M  160  55
2  13  F  152  48
Index(['年齢', '性別', '身長', '体重'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
Index(['Taro', 'Jiro', 'Hana'], dtype='object')
      年齢 性別   身長  体重
Taro  12  M  150  40
Jiro  14  M  160  55
Hana  13  F  152  48


年齢 性別   身長  体重
Taro  12  M  150  40
Jiro  14  M  160  55
Hana  13  F  152  48

In [52]:
df = df.rename(columns={"身長": "height(cm)", "体重": "weight(kg)"})
print(df)
print(len(df))
print(len(df.columns))
print(df.shape)
print(df.info())

      年齢 性別  height(cm)  weight(kg)
Taro  12  M         150          40
Jiro  14  M         160          55
Hana  13  F         152          48
3
4
(3, 4)
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Taro to Hana
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   年齢          3 non-null      int64 
 1   性別          3 non-null      object
 2   height(cm)  3 non-null      int64 
 3   weight(kg)  3 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 120.0+ bytes
None


In [53]:
df.describe()
df["性別"].value_counts()
pd.get_dummies(df["性別"])
print(df[["年齢","height(cm)"]])

print(df.loc[["Taro", "Jiro"],["年齢","height(cm)"]])


      年齢  height(cm)
Taro  12         150
Jiro  14         160
Hana  13         152
      年齢  height(cm)
Taro  12         150
Jiro  14         160


In [54]:
display(df)

df.iloc[:,1]
df.iloc[[0,1],[1,2]]

display(df)
df.iloc[:,[True, False, True, False]]

年齢 性別  height(cm)  weight(kg)
Taro  12  M         150          40
Jiro  14  M         160          55
Hana  13  F         152          48

年齢 性別  height(cm)  weight(kg)
Taro  12  M         150          40
Jiro  14  M         160          55
Hana  13  F         152          48

年齢  height(cm)
Taro  12         150
Jiro  14         160
Hana  13         152

In [55]:
df = df.rename(columns={"年齢": "age", "性別": "sex", "height(cm)": "height", "weight(kg)": "weight"})
display(df)

age sex  height  weight
Taro   12   M     150      40
Jiro   14   M     160      55
Hana   13   F     152      48

In [58]:
df.query("age == 12")
min_height = 150
df.query("height > @min_height")

age sex  height  weight
Jiro   14   M     160      55
Hana   13   F     152      48

In [71]:
Eight = df.columns.str.contains("eight")
print(Eight)
df.iloc[[True, True, False],Eight]

[False False  True  True]


height  weight
Taro     150      40
Jiro     160      55

In [106]:
df.loc["Riki"] = [13, "M", 155, 48] # locで追加できる
df.sort_values(["age", "height"], ascending=[False, True])

age sex  height  weight
Jiro   14   M     160      55
Hana   13   F     152      48
Riki   13   M     155      48
Taro   12   M     150      40